#!/bin/bash

for dataset in dblp aan
do
    mkdir arga/result/$dataset
    mkdir arga2/result/$dataset
    for direct in joined paper_venue paper_author paper_title paper_title_vec paper_abstract_vec paper_bow paper_author_authors paper_year
    do
        mkdir arga/result/$dataset/$direct
        mkdir arga2/result/$dataset/$direct
        mkdir data/$dataset/$direct
    done
done

for dataset in DBLP AAN
do
    for direct in joined paper_venue paper_author paper_title paper_title_vec paper_abstract_vec paper_bow paper_author_authors paper_year
    do
        mkdir Datasets/$dataset/processed/$direct
    done
done

mkdir arga/tmp
mkdir arga2/tmp
